name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}    # 버킷 이름
  CODE_DEPLOY_APPLICATION_NAME: gracememo-server    # CodeDeploy 애플리케이션 이름
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: gracememo-group1 # CodeDeploy 배포 그룹 이름

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle build
      - name: Build with Gradle
        run: ./gradlew clean build

      # AWS 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      # 배포 스크립트에 환경변수 설정 추가
      - name: Make deploy scripts
        run: |
          mkdir -p before-deploy
          echo "#!/bin/bash" > before-deploy/deploy.sh
          echo "export DB_URL='${{ secrets.DB_URL }}'" >> before-deploy/deploy.sh
          echo "export DB_USERNAME='${{ secrets.DB_USERNAME }}'" >> before-deploy/deploy.sh
          echo "export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> before-deploy/deploy.sh
          echo "cd /home/ec2-user/app" >> before-deploy/deploy.sh
          echo "echo '> 현재 구동중인 애플리케이션 pid 확인'" >> before-deploy/deploy.sh
          echo "CURRENT_PID=\$(pgrep -f your-application)" >> before-deploy/deploy.sh
          echo "if [ -z \"\$CURRENT_PID\" ]; then" >> before-deploy/deploy.sh
          echo "    echo '> 현재 구동중인 애플리케이션이 없으므로 종료하지 않습니다.'" >> before-deploy/deploy.sh
          echo "else" >> before-deploy/deploy.sh
          echo "    echo '> kill -15 \$CURRENT_PID'" >> before-deploy/deploy.sh
          echo "    kill -15 \$CURRENT_PID" >> before-deploy/deploy.sh
          echo "    sleep 5" >> before-deploy/deploy.sh
          echo "fi" >> before-deploy/deploy.sh
          echo "echo '> 새 어플리케이션 배포'" >> before-deploy/deploy.sh
          echo "JAR_NAME=\$(ls -tr *.jar | tail -n 1)" >> before-deploy/deploy.sh
          echo "echo '> JAR Name: \$JAR_NAME'" >> before-deploy/deploy.sh
          echo "chmod +x \$JAR_NAME" >> before-deploy/deploy.sh
          echo "nohup java -jar \$JAR_NAME > nohup.out 2>&1 &" >> before-deploy/deploy.sh
          chmod +x before-deploy/deploy.sh


      # 배포 파일 생성
      - name: Make zip file
        run: |
          mkdir -p before-deploy
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r before-deploy *
          cd ../ && mkdir -p deploy
          mv before-deploy/before-deploy.zip deploy/deploy.zip

      # S3에 업로드
      - name: Upload to AWS S3
        run: |
          aws s3 cp \
            deploy/deploy.zip s3://$S3_BUCKET_NAME/

      # CodeDeploy에 배포 요청
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=deploy.zip,bundleType=zip